on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-versions: [ {dotnet-version:'3.1.x',dotnet-sdk:'netcoreapp3.1'}, {dotnet-version:'6.0.x',dotnet-sdk:'net6.0'} ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-versions.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-versions.dotnet-version }}
          DOTNET_SDK: ${{ matrix.dotnet-versions.dotnet-sdk }}
      - name: Run test ${{ matrix.dotnet-versions.dotnet-version }}
        run: make test-cs
