on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: 2.1.x, framework: netcoreapp2.1 }
          - { dotnet: 2.2.x, framework: netcoreapp2.2 }
          - { dotnet: 3.0.x, framework: netcoreapp3.0 }
          - { dotnet: 3.1.x, framework: netcoreapp3.1 }
          - { dotnet: 5.0.x, framework: net5.0 }
          - { dotnet: 6.0.x, framework: net6.0 }
          - { dotnet: 7.0.x, framework: net7.0 }
    name: ${{ matrix.dotnet }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: make test-cs
        env:
          DOTNET_SDK: ${{ matrix.framework }}
